name: cross browser API testing 

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened]
  schedule:
    - cron: '0 2 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Run docker-compose 
        run: docker-compose up -d chrome firefox edge 

      - name: Docker Compose logs
        run: docker-compose logs -f
